<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Cuemon.Extensions.IO" Version="10.7.1" />
    <PackageVersion Include="Codebelt.Extensions.Xunit.App" Version="12.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageVersion Include="MinVer" Version="8.0.0" />
    <PackageVersion Include="Savvyio.Domain" Version="5.0.12" />
    <PackageVersion Include="Savvyio.Extensions.Newtonsoft.Json" Version="5.0.12" />
    <PackageVersion Include="Savvyio.Extensions.Text.Json" Version="5.0.12" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.v3.runner.console" Version="4.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>